# Generated by Django 5.2.1 on 2025-05-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
